org: alxblsk
app: aws-redone-vote
service: aws-redone-vote
frameworkVersion: 2

provider:
  name: aws
  region: us-west-1
  memorySize: 128
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  init:
    handler: src/votes.init
    events:
      - http:
          path: api/v1/votes/{id}
          method: post
          cors:
            origin: '*'
          request:
            parameters:
              paths:
                id: true
  vote:
    handler: src/votes.vote
    events:
      - http:
          path: api/v1/votes/{id}
          method: patch
          cors:
            origin: '*'
          request:
            parameters:
              paths:
                id: true
  list:
    handler: src/votes.list
    events:
      - http:
          path: api/v1/votes/{id}
          method: get
          cors:
            origin: '*'
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3010
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 10m
      heapMax: 20m
      migrate: true
      seed: false
      convertEmptyValues: false

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: votes
        AttributeDefinitions:
          - AttributeName: articleId
            AttributeType: S
        KeySchema:
          - AttributeName: articleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1