org: alxblsk
app: aws-redone-vote
service: aws-redone-vote
frameworkVersion: '2'

provider:
  name: aws
  region: us-west-1
  memorySize: 128
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: api/v1/hello
          method: get
          cors:
            origin: '*'

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3010
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 10m
      heapMax: 20m
      migrate: true
      seed: false
      convertEmptyValues: false

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: votes
        AttributeDefinitions:
          - AttributeName: articleId
            AttributeType: S
        KeySchema:
          - AttributeName: articleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 5